import subprocess
import re
import sys
from pathlib import Path

# Explicitly exclude legacy_scripts and tests
TARGETS = ["app.py", "api_v1.py", "core", "services", "scripts", "mcp_server"]
WHITELIST_FILE = ".dynamic_whitelist.py"

def generate_dynamic_whitelist():
    """Parses Flask files to dynamically whitelist routes and filters."""
    whitelist_names = set()
    
    # Regex to match Flask decorators followed by the function definition
    # e.g., @app.route(...)\n def my_route_handler(
    pattern = re.compile(
        r'@(?:app|api_v1)\.(?:route|template_filter).*?\n\s*def\s+([a-zA-Z0-9_]+)\s*\(', 
        re.DOTALL
    )

    for file_name in ["app.py", "api_v1.py"]:
        file_path = Path(file_name)
        if file_path.exists():
            content = file_path.read_text(encoding='utf-8')
            matches = pattern.findall(content)
            whitelist_names.update(matches)

    # Manually add the background thread targets that Flask doesn't decorate
    whitelist_names.update(["_run_fts_backfill", "_run_scan_worker"])

    # Write to a temporary Vulture-compatible file
    with open(WHITELIST_FILE, "w", encoding='utf-8') as f:
        f.write("# AUTO-GENERATED BY analyze_code.py\n")
        for name in sorted(whitelist_names):
            f.write(f"{name}\n")
            
    return len(whitelist_names)

def run_vulture():
    """Executes Vulture and categorizes the output."""
    print("Running Vulture Analysis...")
    
    # Build command
    cmd = ["vulture"] + TARGETS + [WHITELIST_FILE]
    
    # Run process
    result = subprocess.run(cmd, capture_output=True, text=True)
    output_lines = result.stdout.splitlines()

    certain_dead_code = [line for line in output_lines if "100% confidence" in line]
    unused_imports = [line for line in output_lines if "90% confidence" in line]

    print("\n" + "="*50)
    print(" 100% CONFIDENCE (Confirmed Dead Code/Variables)")
    print("="*50)
    if certain_dead_code:
        print("\n".join(certain_dead_code))
    else:
        print(" None found.")

    print("\n" + "="*50)
    print(" 90% CONFIDENCE (Unused Imports)")
    print("="*50)
    if unused_imports:
        print("\n".join(unused_imports))
    else:
        print(" None found.")

    # Clean up the temporary whitelist so it doesn't clutter your repo
    Path(WHITELIST_FILE).unlink(missing_ok=True)

if __name__ == "__main__":
    count = generate_dynamic_whitelist()
    print(f"Dynamically whitelisted {count} Flask routes and filters.")
    run_vulture()
